env:
  browser: true
  es2021: true
extends:
  - "react-app"
  - "react-app/jest"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules:
  "@typescript-eslint/consistent-type-imports": "error"
overrides:
  - files:
      - "**/*.stories.*"
    rules:
      import/no-anonymous-default-export: "off"
